sudo: false
dist: trusty
language: ruby
addons:
  chrome: stable
  apt:
    packages:
    - libclamav-dev
    - clamav
cache:
- bundler: true
services:
- redis-server
- postgresql
rvm:
- 2.4.2
before_script:
- bundle exec rake db:create
before_install:
- gem update --system
- gem install bundler
- google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222
  http://localhost &
after_success:
- |
  if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
    openssl aes-256-cbc -K $encrypted_a9d30a8f0000_key -iv $encrypted_a9d30a8f0000_iv -in nurax-dev-deploy_rsa.enc -out nurax-dev-deploy_rsa -d
    bundle update hyrax
    git commit -a -m "Updating hyrax to latest SHA"
    bundle exec cap nurax-dev deploy
  fi
jdk:
- oraclejdk8
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
